### PR TITLE
follow git worktree pointers

### LINKED ISSUE #64: Will not recognize projects using gitdir
I know this is not a common use case, but because my job is super married to TFS right now. Due to a recent loss of a lot of code, I decided to set up a day-to-day use local git repo, that would be completely detached from the TFS folder, in case I need to scorch, but fully watching all my changes. 

I've set up my source folders to have a .git file that points to another directory outside of the project containing the .git folder using the "gitdir" property, allowing me to use GIT in my day-to-day operations and use TFS only when getting latest from my team or when I'm checking in code that has finished.

We do use VSTS but mostly for sprint planning but I have also set it up as the origin of my local GIT repo(basically uploading everything that is currently on the TFS server, so they are basically in parity), which fits the requirements for the extension. 

Opening VS Code in the project with the .git file with the folder pointer, the extension will not recognize the project at all. If I open VS Code in the folder that the .git file points to, the extension begins to work. 

----------------------------------------
For testing purposes, here is the steps to take to set up a repo in these conditions:

1) Outside of the project folder, create a folder for the git repo. 
2) Open the folder and do "git init", set it up with the info you would do if initializing the repo in the project folder.
3) In the project folder with the actual code, create a new file called ".git".
4) Open the file and put the following line:
"gitdir: directory/to/the/repo.git"

You should now be able to use GIT within the project folder as if the .git folder was stored in that directory.

----------------------------------------

It would be great if you could at least take a look at possibly supporting this. I was super interested when I saw the extension because it helps integrate the process I work through everyday into VS Code.

Thanks,
Tyler Robinson

### LINKED ISSUE #387: Cannot load extension in git worktree
When opening a folder that is a git working tree (not the main one), the extension does not load and throws an error:

image

### PR DESCRIPTION
**Pull request by jshall**
Fixes #64
Fixes #387

### CODE REVIEW

**Comment by abdulkareemnalband** [comment]
Any updates on this?

**Comment by edenvicary** [comment]
I'd really like this, I'm trying to use Azure Repos but it only works in my main repo not on any of my worktrees.

**Comment by edenvicary** [comment]
@jshall

**Comment by edenvicary** [comment]
I'd really like this, I'm trying to use Azure Repos but it only works in my main repo not on any of my worktrees. @jshall @jeffyoung @jpricket

**Comment by jshall** [comment]
@jrbriggs @jeschu1 what would it take to get this PR in the next release?

**Pull request closed without merging**
